name: "Nix Build"

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: webkeyfinder
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build ./#key-finder-web
